Controllers/CommunitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab4.Data;
using Lab4.Models;
using Lab4.Models.ViewModels;

namespace Lab4.Controllers
{
    public class CommunitiesController : Controller
    {
        private readonly SchoolCommunityContext _context;

        public CommunitiesController(SchoolCommunityContext context)
        {
            _context = context;
        }

        // GET: Communities
        public async Task<IActionResult> Index(string ID)
        {
            var viewModel = new CommunityViewModel();
            viewModel.Community = await _context.Community
                  .Include(i => i.CommunityMembership)
                  .AsNoTracking()
                  .OrderBy(i => i.Title)
                  .ToListAsync();
            viewModel.Student = await _context.Student
                .Include(i => i.CommunityMembership)
                .AsNoTracking().OrderBy(i => i.FirstName)
                .ToListAsync();

            if (ID != null)
            {
                ViewData["CommunityID"] = ID;
                viewModel.CommunityMembership = viewModel.Community.Where(
                    x => x.ID.Equals(ID)).Single().CommunityMembership;

            }

            return View(viewModel);
        }

        // GET: Communities/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = await _context.Community
                .FirstOrDefaultAsync(m => m.ID == id);
            if (community == null)
            {
                return NotFound();
            }

            return View(community);
        }

        // GET: Communities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Communities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Budget")] Community community)
        {
            if (ModelState.IsValid)
            {
                _context.Add(community);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(community);
        }

        // GET: Communities/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = await _context.Community.FindAsync(id);
            if (community == null)
            {
                return NotFound();
            }
            return View(community);
        }

        // POST: Communities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,Title,Budget")] Community community)
        {
            if (id != community.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(community);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommunityExists(community.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(community);
        }


        // GET: Communities/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = await _context.Community
                .FirstOrDefaultAsync(m => m.ID == id);
            if (community == null)
            {
                return NotFound();
            }

            return View(community);
        }

        // POST: Communities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var community = await _context.Community.FindAsync(id);
            _context.Community.Remove(community);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //public async Task<IActionResult> EditMemberships(int ID)
        //{
        //    //viewModel.studentMembershipViewModel = await _context.StudentMembership.ToListAsync();
        //    var viewModel = new CommunityViewModel();
        //    viewModel.Community = await _context.Community
        //          .Include(i => i.CommunityMembership)
        //          .AsNoTracking()
        //          .OrderBy(i => i.Title)
        //          .ToListAsync();
        //    viewModel.Student = await _context.Student.ToListAsync();

        //    if (ID >= 0)
        //    {
        //        viewModel.EditStudent = _context.Student.SingleOrDefault(x => x.ID.Equals(ID));
        //        //viewModel.EditStudent.ID = ID;
        //    }
        //    //viewModel.EditStudent = await _context.Student.Where(b => b.ID.Equals(ID));

        //    return View(viewModel);
        //}

        //public async Task<IActionResult> AddMembership(int studentId, string communityId)
        //{
        //    var communityMemberShip = new CommunityMembership();
        //    communityMemberShip.StudentID = studentId;
        //    communityMemberShip.CommunityID = communityId;
        //    _context.CommunityMembership.Add(communityMemberShip);
        //    _context.SaveChanges();

        //    //return RedirectToAction(nameof(EditMemberships));
        //    //return View();
        //    return View();
        //}

        private bool CommunityExists(string id)
        {
            return _context.Community.Any(e => e.ID == id);
        }
    }
}

Controllers/StudentsController.cs
using Lab4.Data;
using Lab4.Models;
using Lab4.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Lab4.Controllers
{
    public class StudentsController : Controller
    {
        private readonly SchoolCommunityContext _context;

        public StudentsController(SchoolCommunityContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index(int? ID)
        {
            var viewModel = new CommunityViewModel();
            viewModel.Community = await _context.Community
                  .Include(i => i.CommunityMembership)
                  .AsNoTracking()
                  .OrderBy(i => i.Title)
                  .ToListAsync();
            viewModel.Student = await _context.Student
                .Include(i => i.CommunityMembership)
                .AsNoTracking().OrderBy(i => i.FirstName)
                .ToListAsync();

            if (ID > 0)
            {
                ViewData["StudentID"] = ID;
                viewModel.CommunityMembership = viewModel.Student.Where(
                    x => x.ID.Equals(ID)).Single().CommunityMembership;

            }

            return View(viewModel);
            /*return View(await _context.Student.ToListAsync());*/
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.ID == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,LastName,FirstName,EnrollmentDate,FullName")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }


        public async Task<IActionResult> EditMemberships(int ID)
        {

            //viewModel.studentMembershipViewModel = await _context.StudentMembership.ToListAsync();
            var viewModel = new CommunityViewModel();
            //viewModel.Community = await _context.Community
            //      .Include(i => i.CommunityMembership)
            //      .AsNoTracking()
            //      .OrderBy(i => i.Title)
            //      .ToListAsync();
            //viewModel.Student = await _context.Student.ToListAsync();

            //if (ID >= 0)
            //{
            //    viewModel.EditStudent = _context.Student.SingleOrDefault(x => x.ID.Equals(ID));
            //}

            viewModel.Community = await _context.Community
                  .Include(i => i.CommunityMembership)
                  .AsNoTracking().OrderBy(i => i.Title)
                  .ToListAsync();
            viewModel.Student = await _context.Student
                .Include(i => i.CommunityMembership)
                .AsNoTracking().OrderBy(i => i.FirstName)
                .ToListAsync();

            if (ID > 0)
            {
                ViewData["StudentID"] = ID;
                viewModel.CommunityMembership = viewModel.Student.Where(
                    x => x.ID.Equals(ID)).Single().CommunityMembership;
                
                //if(viewModel.CommunityMembership.Count() == 0)
                //{
                //    viewModel.IsMember = false;
                //}
                //else
                //{
                //    viewModel.IsMember = true;
                //}
                viewModel.EditStudent = _context.Student.SingleOrDefault(x => x.ID.Equals(ID));


            }


            return View(viewModel);
        }

        public async Task<IActionResult> AddMembership(int studentId, string communityId)
        {
            var viewModel = new CommunityViewModel();
            //viewModel.Student = await _context.Student.ToListAsync();
            //viewModel.EditStudent = _context.Student.SingleOrDefault(x => x.ID.Equals(studentId));
         

            var student = _context.Student.SingleOrDefault(x => x.ID == (studentId));
            var community =  _context.Community.SingleOrDefault(x => x.ID.Equals(communityId));
            var communityMemberShip = new CommunityMembership();
            communityMemberShip.Student = student;
            communityMemberShip.StudentID = studentId;
            communityMemberShip.Community = community;
            communityMemberShip.CommunityID = communityId;
            _context.CommunityMembership.Add(communityMemberShip);
            _context.SaveChanges();

            //return RedirectToAction(nameof(EditMemberships));
            return RedirectToAction("EditMemberships", new { id = studentId });

            //return View();
        }

        public async Task<IActionResult> RemoveMembership(int studentId, string communityId)
        {

            var viewModel = new CommunityViewModel();
            viewModel.Student = await _context.Student.ToListAsync();
            viewModel.EditStudent = _context.Student.SingleOrDefault(x => x.ID.Equals(studentId));


            var student = _context.Student.SingleOrDefault(x => x.ID == (studentId));
            var community = _context.Community.SingleOrDefault(x => x.ID.Equals(communityId));
            var communityMemberShip = new CommunityMembership();
            communityMemberShip.Student = student;
            communityMemberShip.Community = community;
            //communityMemberShip.StudentID = studentId;
            //communityMemberShip.CommunityID = communityId;
            _context.CommunityMembership.Remove(communityMemberShip);
            _context.SaveChanges();

            //viewModel.CommunityViewModel.Memberships = await _context.Community

                  //.ToListAsync();

            //return RedirectToAction(nameof(EditMemberships));
            return RedirectToAction("EditMemberships", new { id = studentId });

        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,LastName,FirstName,EnrollmentDate,FullName")] Student student)
        {
            if (id != student.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.ID == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Student.FindAsync(id);
            _context.Student.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return _context.Student.Any(e => e.ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment 1</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/sketchy/bootstrap.min.css" integrity="sha384-RxqHG2ilm4r6aFRpGmBbGTjsqwfqHOKy1ArsMhHusnRO47jcGqpIQqlQK/kmGy9R" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    @*    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/minty/bootstrap.min.css" integrity="sha384-H4X+4tKc7b8s4GoMrylmy2ssQYpDHoqzPa9aKXbDwPoPUA3Ra8PA5dGzijN+ePnH" crossorigin="anonymous">
    *@
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">

</head>
<body style="background-image: url(https://pbs.twimg.com/media/DMDIKcyWsAEsKDj.jpg); height: 100%;
        background-size: cover;">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="/Home" style=" margin-right: 35px;">SchoolCommunity</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Home" style="margin-right: 22px;">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Students" style="margin-right: 22px;">Students</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Communities">Communities</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <br /><br />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @RenderSection("Scripts", required: false)





    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - Lab4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    @*  <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@
    @*@RenderSection("Scripts", required: false)*@
    <!--<header>-->
    @*@Html.ActionLink("Home", "Index", "Home") &nbsp
        @Html.ActionLink("Show the song!", "Razor", "Home") &nbsp
        @Html.ActionLink("Persons", "CreatePerson", "Home") &nbsp*@


    <!--<b><a class="navbar-brand" style="text-decoration:none; color: inherit;" asp-controller="Home" asp-action="Index">SchoolCommunity</a></b> &nbsp; &nbsp;
        <a class="navbar-brand" style="text-decoration:none; color: inherit;" asp-controller="Home" asp-action="Index">Home</a>  &nbsp;
        <a class="navbar-brand" style="text-decoration:none; color: inherit;" asp-controller="Students" asp-action="Index">Students</a>  &nbsp;
        <a class="navbar-brand" style="text-decoration:none; color: inherit;" asp-controller="Communities" asp-action="Index">Communities</a>  &nbsp;


    </header>
    <div class="content">
        @RenderBody()
    </div>
    <footer>
        <div>-->
    @*<p>
            Footer!
        </p>*@
    <!--</div>
    </footer>-->
</body>
</html>